app/models.py
from .import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

class Quotes:
    def __init__(self,id,quote,author):
        self.id=id
        self.quote=quote
        self.author=author


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    blog = db.relationship('Blog',backref='user',lazy='dynamic')
    pass_secure =db.Column(db.String(255))
    email=db.Column(db.String,unique=True)
    bio=db.Column(db.String(255))
    profile_pic_path=db.Column(db.String())
    comment = db.relationship('Comment',backref = 'user',lazy = "dynamic")
    

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    
    def __repr__(self):
        return f'User {self.username}'

class Blog(db.Model):
    __tablename__ = 'blogs'
    id = db.Column(db.Integer,primary_key = True)
    title=db.Column(db.String(255))
    blog = db.Column(db.String)
    author=db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comment = db.relationship('Comment',backref = 'blog',lazy = "dynamic")

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    def delete_blog(self):
        db.session.delete(self)
        db.session.commit()
    

    def __repr__(self):
        return f'Blog {self.blog}'

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.Text(),nullable = False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable = False)
    blog_id = db.Column(db.Integer,db.ForeignKey('blogs.id'),nullable = False)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    def delete_comment(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'comment:{self.comment}'        

    

    
        

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SelectField,SubmitField
from wtforms.validators import InputRequired

class BlogForm(FlaskForm):

    title = StringField('Blog title',validators=[InputRequired()])
    blog = TextAreaField('Blog content', validators=[InputRequired()])
    author=StringField('Author',validators=[InputRequired()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment = TextAreaField('Your comment' ,validators= [InputRequired()])
    submit = SubmitField('Submit')

class UpdateBlog(FlaskForm):
    title = StringField('Enter title',validators=[InputRequired()])
    blog = TextAreaField('Edit your blog',validators = [InputRequired()])
    submit = SubmitField('Submit')        

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [InputRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos=UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    # Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required,current_user
from ..models import Blog,User,Comment
from .forms import BlogForm,CommentForm,UpdateProfile
from ..import db,photos
from ..requests import get_quotes
import datetime

@main.route('/')
def index():
    title='Fridah`s Blog Website'
    blog=Blog.query.all()
    random_quotes=get_quotes()

    return render_template('index.html',title = title,quotes=random_quotes, blog=blog)

@main.route('/blog/<int:blog_id>',methods=['GET'])
@login_required
def blog(blog_id):
    blog = Blog.query.get(blog_id)
    form=CommentForm()

    
    return render_template('blog.html',blog = blog,form=form)

@main.route('/blog/new',methods=['GET','POST'])
@login_required
def new_blog():
    form=BlogForm()
    if form.validate_on_submit():
        title = form.title.data
        blog = form.blog.data
        
        user_id=current_user
        
        new_blog= Blog(title = title,blog = blog,user_id=current_user._get_current_object().id)
        new_blog.save_blog()
        return redirect(url_for('main.index'))

    return render_template('new_blog.html',form=form)    


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/comment/<int:blog_id>', methods = ['POST','GET'])
@login_required
def comment(blog_id):
  comments = Comment.query.filter_by(blog_id=blog_id).all()
  form = CommentForm()
  if form.validate_on_submit():
    comment = form.comment.data

    new_comment_object= Comment(comment=comment, blog_id=blog_id, user_id = current_user._get_current_object().id)

    new_comment_object.save_comment()
    return redirect(url_for('main.comment', blog_id=blog_id))

  return render_template('comment.html', form=form, comments=comments)

@main.route('/<blog_id>/',methods=['GET','DELETE'])
@login_required
def delete_blog(blog_id):
    deleteBlog = Blog.query.filter_by(id=blog_id).first()
    if deleteBlog:
        db.session.delete(deleteBlog)
        db.session.commit()
        return redirect(url_for('main.index'))
    else:
        pass
    return redirect(url_for('main.index'))

    
@main.route('/blog/edit/<int:id>',methods = ['GET','POST'])
@login_required
def edit_blogs(id):
    if not current_user:
        abort(404)

    updateBlog= Blog.query.get(id)

    form = BlogForm()

    if form.validate_on_submit():
        updateBlog.title = form.title.data
        updateBlog.blog = form.blog.data

        db.session.add(updateBlog)
        db.session.commit()

        return redirect(url_for('main.index',id=updateBlog.id))
    

    return render_template('new_blog.html',form = form,action='Edit')              

app/templates/base.html
{%extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
    integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
{% endblock styles%}

app/templates/blog.html
{% extends 'base.html'%}
{% block content %}
<div class="card" style="width: 18rem;">
	<div class="card-body">
	  <h5 class="card-title">{{blog.title}}</h5>
	  <p class="card-text">{{blog.blog}}</p>
	  
	</div>
  </div>
{%endblock%}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
<div class="container">
    <div class="row">
        {% if comments %}
            <div class="col-md-7" >
                <h3 class="text-center" style="color: rgb(0, 204, 255);">All comments for the blog;</h3>
                <hr>
                    {% for comment in comments %}
                        <div class="card w-90 mb-3" >
                            <div class="card-body">
                                <h5>Title: {{ comment.blog.title }}</h5>
                                 <p class="card-title">Comment: {{ comment.comment }}</p>
                                 <p class="card-text">Writer: {{ comment.user.username }}</p>
                            </div>
                        </div>
                    {% endfor %}
            </div>
            <div class="col-md-5  commentform">{{wtf.quick_form(form)}}</div>
    </div>
    {%else%}
    <div class="card w-90 mb-3">
        <div class="card-body">
            <p class="card-title" style="color: rgb(0, 204, 255);">Comment here;</p>
        </div>
    </div>
    <div class="col-md-5">{{wtf.quick_form(form)}}</div>
    {%endif%}
</div>
       
    {% endblock%}

app/templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% import 'macros.html' as macro %}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content%}
<div class="jumbotron" style="font-style: italic;background-color: transparent;">
        <div class="card" style="margin-top: 1px;padding-top: 0%;"></div>
			<figure class="text-center">
				<blockquote class="blockquote">
					<p style="color: rgb(0, 204, 255);">Blog-Web</p>
					<p>{{ quotes.quote }}</p>
				</blockquote>
				<figcaption class="blockquote-footer" style="font-style: bold;">
					<cite title="Source Title"> ~~{{quotes.author}}</cite>
				</figcaption>
			</figure>
		</div>
	</div>
<h1 style="margin-bottom: 2px;text-align: center;color: rgb(0, 204, 255);">I BLOG ABOUT IT</h1>
<hr>


        <div class="div">
            {{macro.displayblog(blog)}}
        </div>
{% endblock %}

app/templates/macros.html
{% macro displayblog(blog)%}
{% if  blog%}
    {%for blog in blog%}
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card" >
            <div class="well well-lg">
                <h4>{{blog.title}}</h4>
                <p>{{blog.blog}}</p>
				<p>Created by: {{blog.author}}</p>
                <a href="{{url_for("main.comment",blog_id=blog.id)}}"class="btn btn-info -center" style="margin-top: 2%;"id=btn>Comment</a>
                <a href="{{url_for("main.edit_blogs",id=blog.id)}}"class="btn btn-info -center" style="margin-top: 2%;">Edit</a>
                <a href="{{url_for("main.delete_blog",blog_id=blog.id)}}"class="btn btn-info -center" style="margin-top: 2%;">Delete</a>
            
            </div>
        </div>
    {%endfor%}
{%endif%}
{%endmacro%}

app/templates/navbar.html
<nav class="navbar navbar-inverse default-color">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="" class="navbar-brand"style="color: rgb(0, 204, 255);"><Strong><b>Blog-Web</b></Strong></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/"style="color: rgb(0, 204, 255);"><b>Home</b></a></li>
                <li><a href="{{url_for('main.new_blog')}}"style="color: rgb(0, 204, 255);">New Blog</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="nav navbar-nav "><a href="#" class="collapse-toggle" data-toggle="navbar-collapse"style="color: rgb(0, 204, 255);">{{current_user.username| capitalize}} <span></span></a>
                </li>
                    <ul class="nav navbar-nav ">
                        <li><a href="{{url_for('main.profile',uname=current_user.username)}}"style="color: rgb(0, 204, 255);">🤵 Profile</a></li>
                        
                        <li><a href="{{url_for('auth.logout')}}"style="color: rgb(0, 204, 255);">🙎‍♂️ Sign out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">🙎‍♂️ Sign in</a></li>
            </ul>
                {%endif%}
              
        </div>
        
        </div>
    </div>
</nav>

app/templates/new_blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="jumbotron" style="color: rgb(0, 204, 255);">
    <h1 style="text-align: center;">Add Your Blog Here</h1>
</div>
<div class="container">
    <div class="row">

        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-md-2"></div>

    </div>
</div>
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
  <!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}
    
  </div>

</div>
</div>
{% endblock %}
  

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}